### ISSUE TITLE
Add a binding for `mix test —failed`?

### ISSUE THREAD

**Issue by vfsoraki** [ananthakumaran/exunit.el#12]
I think this is a good command to have by default. I can create a PR for this, but first I wanted to know the opinions.

**Comment by ananthakumaran** [comment]
could you check out https://github.com/ananthakumaran/exunit.el/pull/13. The would allow you to add `--failed` option to any existing command.

**Comment by vfsoraki** [comment]
That’s actually very good IMO. I like the options.

**Comment by ananthakumaran** [comment]
merged to master
