### ISSUE TITLE
Add ability to compile and run tests inside Docker container

### ISSUE THREAD

**Issue by dcaixinha** [ananthakumaran/exunit.el#3]
It would be great to be able to use `exunit.el` inside a Docker container.

Copying the idea from [RSpec Mode](https://github.com/pezra/rspec-mode#docker), maybe `exunit.el` could have some parameters (such as `exunit-use-docker-when-possible`, `exunit-docker-container`, `exunit-docker-command` and `exunit-docker-cwd`) which would essentially turn the test commands prepended by `docker exec -it <exunit-docker-container> bash -c "cd <exunit-docker-cwd> && <command_to_run_test> "`.

What do you think?

**Comment by dcaixinha** [comment]
Hey @ananthakumaran, what does the 'PR accepted' label mean? You would accept such contribution? My Emacs Lisp-fu is quite weak, but I think I can copy the approach they had in `RSpec mode` and open the PR to get some feedback. Sounds good?

**Comment by ananthakumaran** [comment]
Yes, go ahead and open a PR. This library is mostly based on rspec mode.

**Comment by dcaixinha** [comment]
Hey @ananthakumaran, I now have a working version of `exunit.el` running the tests inside a docker container! :tada: while developing this I realized how useful it would be if I could also access any breakpoints I have set when debugging tests.

Since this is using a compilation buffer, the code stops there but then I can't access it. Do you have any idea / suggestion on how this would be possible? FYI I've manually created an `eshell` on the side and input the same command, and there I can interact with the breakpoint. Thanks :raised_hands:

**Comment by ananthakumaran** [comment]
I tried to debug the issue, but seems like too many things going on.

1) TERM is set to dumb by default, which results in IEx not able to start
2) If I change the TERM, it is still not able to read input.

I haven't spend much time to find the root cause so far.
