### ISSUE TITLE
Add minor mode similar to rspec-mode

### ISSUE THREAD

**Issue by dgutov** [ananthakumaran/exunit.el#4]
For ease of setting up the keybindings, at least.

**Comment by ananthakumaran** [comment]
It was there in the initial version https://github.com/ananthakumaran/exunit.el/commit/8cae9a7420c2872984fdb9a93e20a78c4f714560#diff-e4154b7f3ae55e3b516e29076874cb25L160 but the during the melpa review, it got removed. I hadn't thought about key bindings, will add it back

**Comment by dgutov** [comment]
Cool, thanks in advance.

`exunit-mode` surely won't be unused this way.

**Comment by dgutov** [comment]
Thanks.

Could you add the default key bindings as well? With `(defcustom exunit-key-command-prefix`, etc.

**Comment by dgutov** [comment]
@ananthakumaran

**Comment by ananthakumaran** [comment]
I was going to do it, but then got sidetracked. Feel free to open PR if you
got some time, otherwise I will get to it soon.
