### ISSUE TITLE
Stop the cursor from going purple when tests are run

### ISSUE THREAD

**Issue by axelson** [ananthakumaran/exunit.el#6]
In my environment with Spacemacs when I run the test, for example with `exunit-verify` the cursor turns purple. This seems to be related to the `evil-mode` state changing, but I'm not sure what is triggering that. Possibly something with the read-only trigger? Is there a way to stop the cursor/state from changing?

**Comment by axelson** [comment]
FYI, I'm currently working around this with:
```
  (defun jax-restore-cursor ()
    ;; Should be able to utilize (symbol-value evil-normal-state-cursor) somehow
    (set-cursor-color "DarkGoldenrod2"))

  (advice-add 'exunit-rerun :after #'jax-restore-cursor)
  (advice-add 'exunit-verify :after #'jax-restore-cursor)
  (advice-add 'exunit-verify-all :after #'jax-restore-cursor)
  (advice-add 'exunit-verify-single :after #'jax-restore-cursor)
  (advice-add 'rspec-rerun :after #'jax-restore-cursor)
  (advice-add 'rspec-verify :after #'jax-restore-cursor)
  (advice-add 'rspec-verify-all :after #'jax-restore-cursor)
  (advice-add 'rspec-verify-single :after #'jax-restore-cursor)
```

**Comment by ananthakumaran** [comment]
I don't use evil and don't experience this problem. It would be nice if we can find the root cause.

**Comment by axelson** [comment]
This is probably not really related to exunit.el and I've worked around it by switching to Doom Emacs which doesn't have this issue.
