### ISSUE TITLE
Feature request: a way to run the tests in order

### ISSUE THREAD

**Issue by axelson** [ananthakumaran/exunit.el#9]
I would like to occasionally run the tests in an individual file in order. This can be accomplished by passing `--seed` to mix test: 

> --seed - seeds the random number generator used to randomize the order of tests; --seed 0 disables randomization

from https://hexdocs.pm/mix/Mix.Tasks.Test.html

Would this be best as a new function like `exunit-verify-non-random`? Or some other method?

**Comment by ananthakumaran** [comment]
There are a lot of options available for `mix test` command and adding a new function for each option would be unsustainable. We also have 4 different functions `exunit-verify-{all, single, all-in-umbrella}` to specify the scope.

For short term fix, you could use

```elisp
(defun my-exunit-verify-non-random ()
  (let ((exunit-mix-test-default-options '("--seed" "0")))
    (exunit-verify))
```

For long term, we need to come up with a proper UX. Using magit like popup is one approach and that could be enabled if the command is executed with a prefix. I am open to other approaches that doesn't lead to any combinatorial explosion of fuctions.

**Comment by axelson** [comment]
Yes, avoiding a combinatorial explosion is a great point. Thanks for the short-term fix, it works great!
